[package]
name = "aoc2022"
version = "0.0.0"
authors = ["Axel Lindeberg", "Joseph Chamochumbi"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
# lib proc-macro dependencies
syn = { version = "1.0", features = ["full"] }
quote = "1.0"

