[package]
authors = ["Axel Lindeberg", "Joseph Chamochumbi"]
edition = "2021"
name = "aoc2022"
version = "0.0.0"

[lib]
proc-macro = true

[dependencies]
# lib proc-macro dependencies
quote = "1.0"
serde_json = "1.0"
syn = {version = "1.0", features = ["full"]}
