[package]
authors = ["Joseph Chamochumbi <sephxd1234@gmail.com>"]
edition = "2018"
name = "day-10"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
aoc = {git = "https://github.com/icyJoseph/advent-of-code.git"}
